name: Auto Minify
run-name: "Github Action: Auto Minified JS and CSS files"
on: [push]
jobs:
  auto-minify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Auto Minify js
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: 'private/scripts'
          output: 'public/scripts'
          overwrite: true
      - name: Auto Minify css
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: 'private'
          output: 'public'
          overwrite: true
          maxdepth: 1
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}